---
version: '3'
services:
  jupyter:
    build: '.'
    environment:
      PYTHONPATH: '/opt/notebooks'
    volumes:
      - '../notebooks/:/opt/notebooks'
    working_dir: '/opt/notebooks'
    ports:
      - '8888:8888'
...
